
# html lang
language: zh-Hans

# main menu navigation
menu:
  home: /
  tags: /tags
  search: /search
  about: /about
  # archives: /archives

# Miscelaneous
favicon: /logo.png

# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
- //cdn.bootcss.com/pure/1.0.0/pure-min.css
- /css/microb.css

# scripts loaded in the end of the body
scripts:
#- //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
#- /js/microb.js

# switch
show_excerpt: false
show_date: true

# links
links:
  Hexo: http://hexo.io
  Theme microb: https://github.com/microacup/hexo-theme-micorb